module.exports = {
  projects: [
    '<rootDir>/apps/journal',
    '<rootDir>/apps/backend-functions',
    '<rootDir>/libs/interfaces',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/user',
    '<rootDir>/libs/collective-goal',
    '<rootDir>/libs/utils',
    '<rootDir>/libs/goal',
    '<rootDir>/libs/post',
    '<rootDir>/libs/discussion',
    '<rootDir>/libs/milestone',
    '<rootDir>/libs/support',
    '<rootDir>/libs/notification',
    '<rootDir>/libs/media',
    '<rootDir>/libs/exercises',
    '<rootDir>/libs/template',
  ],
};
