/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Goal',
      link: {type: 'generated-index', description: 'Create, Roadmap, Story, Share / Follow / Join, Chat'},
      items: [{type: 'autogenerated', dirName: 'goal'}],
    },
    {
      type: 'category',
      label: 'Support',
      link: {type: 'generated-index', description: 'Incentivie the achievers of a goal more by adding supports'},
      items: [{type: 'autogenerated', dirName: 'support'}],
    },
    {
      type: 'category',
      label: 'Exercises',
      link: {type: 'generated-index', description: 'Affirmations, Daily Gratitude, Dear Future Self and Wheel of Life explained'},
      items: [{type: 'autogenerated', dirName: 'exercises'}],
    },
    {
      type: 'category',
      label: 'Profile',
      link: {type: 'generated-index', description: 'Add a profile picture, change username, and more'},
      items: [{type: 'autogenerated', dirName: 'profile'}],
    },
    {
      type: 'category',
      label: 'Create the perfect goal',
      link: {type: 'generated-index', description: 'The purpose is not to make you even more busy and to do even more in your life. Instead the purpose is to actually finish your goals.'},
      items: [{type: 'autogenerated', dirName: 'more/goal-setting'}],
    },
  ],
  apiSidebar: [
    {type: 'autogenerated', dirName: 'api'},
  ],
};

export default sidebars;
